name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Git user
        run: |
          git config --global user.name "Mario"
          git config --global user.email "6395323+mario-huang@users.noreply.github.com"
      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/yonggekkk/Cloudflare_vless_trojan.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
